### ISSUE TITLE
Need a dubbo 2.7.3 example

### ISSUE THREAD

**Issue by loongs-zhang** [fury-project/dubbo-serialization-fury#14]

**Comment by chaokunyang** [comment]
We don't provide support for dubbo2, Currently we only provided integration fury with dubbo3

**Comment by loongs-zhang** [comment]
Got it.

发自我的iPhone


------------------ Original ------------------
From: Shawn ***@***.***&gt;
Date: Fri,Nov 17,2023 0:30 PM
To: fury-project/dubbo-serialization-fury ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [fury-project/dubbo-serialization-fury] Need a dubbo 2.7.3example (Issue #14)





 
We don't provide support for dubbo2, Currently we only provided integration fury with dubbo3

**Comment by chaokunyang** [comment]
The integration for dubbo2 is not complex, you can integrate it with yourself, or use fury in your application code
